import { LevelConfig, LevelTwist } from '../types';

// Educational Facts & Tips Pool
const FACTS_AND_TIPS: { fact: string; tip: string }[] = [
  {
    fact: 'Over 2.2 billion people worldwide lack access to safely managed drinking water at home.',
    tip: 'Turn off the faucet while brushing teeth to save up to 8 gallons of clean water every single day!'
  },
  {
    fact: 'In many arid communities, women and children walk an average of 3.7 miles daily just to fetch water.',
    tip: 'Fix leaky faucets promptly! A single dripping faucet can waste more than 3,000 gallons of water a year.'
  },
  {
    fact: 'Severe droughts affect over 55 million people globally every year, threatening crops and livestock.',
    tip: 'Collect rainwater in barrels for gardening and washing tools rather than using treated potable tap water.'
  },
  {
    fact: 'Unsafe water sources cause millions of preventable illnesses every year, making clean water filtration essential.',
    tip: 'Never dispose of motor oil, paints, or harsh household chemicals down household drains or on the soil.'
  },
  {
    fact: 'Conserving water preserves freshwater ecosystems, protects wildlife, and ensures a secure future for everyone.',
    tip: 'Take shorter 5-minute showers instead of long baths to save 1,000+ gallons of clean water every month.'
  },
  {
    fact: 'Agriculture accounts for roughly 70% of all freshwater withdrawals globally.',
    tip: 'Water outdoor plants early in the morning or late evening to minimize moisture loss from rapid evaporation.'
  },
  {
    fact: 'Groundwater provides drinking water for more than 50% of the world’s population.',
    tip: 'Use a broom instead of a hose to clean driveways, sidewalks, and patios to conserve dozens of gallons.'
  },
  {
    fact: 'It takes approximately 2,700 liters of water to produce a single cotton t-shirt.',
    tip: 'Only run washing machines and dishwashers with full loads to maximize water and energy efficiency.'
  },
  {
    fact: 'Wetlands act as natural water filters, removing pollutants and buffering against seasonal flooding.',
    tip: 'Choose drought-tolerant native plants for gardens—they thrive on natural rainfall with minimal watering.'
  },
  {
    fact: 'Desalination produces clean water from seawater but requires immense energy and specialized tech.',
    tip: 'Install aerators on your sink faucets to cut water flow by 30% to 50% without losing water pressure.'
  },
  {
    fact: 'More than 80% of wastewater generated by society flows back into the ecosystem without being treated.',
    tip: 'Keep a pitcher of drinking water in the refrigerator instead of running the tap until water gets cold.'
  },
  {
    fact: 'Forests play an indispensable role in capturing, filtering, and releasing fresh rainwater into rivers.',
    tip: 'Support local wetland and forest conservation programs that protect vital community watersheds.'
  }
];

const ZONE_NAMES = [
  'The Sunlit Oasis',           // Levels 1-20
  'Canyon Aquifers',            // Levels 21-40
  'The Scorched Wasteland',     // Levels 41-60
  'The Industrial Delta',       // Levels 61-80
  'Grand Reservoir Sanctuary'   // Levels 81-100
];

const LEVEL_SUBTITLES = [
  'The First Drop',             // Level 1 (Required)
  'The Longer Journey',         // Level 2 (Required)
  'Water Is Running Low',       // Level 3 (Required)
  'The Water Is Contaminated',  // Level 4 (Required)
  'Save the Community',         // Level 5 (Required)
  'Speed Rush', 'Oasis Springs', 'Snake Crossway', 'Scorched Dunes', 'Milestone Reservoir I',
  'Crystal Creek', 'Golden Basin', 'Fast Slither', 'Dry Plateau', 'Sludge Basin',
  'Swift River', 'Hidden Wellspring', 'Viper Lair', 'Arid Steppes', 'Milestone Reservoir II',
  'Canyon Brook', 'Emerald Pool', 'Rattlesnake Pass', 'Cracked Valley', 'Toxic Ravine',
  'Quick Stream', 'Verdant Spring', 'Snake Alley', 'Dust Gale', 'Milestone Reservoir III',
  'Mountain Spring', 'Echo Creek', 'Agile Vipers', 'Sunbaked Ridge', 'Chemical Runoff',
  'Rapid Current', 'Pure Cascade', 'Serpent Maze', 'Drought Cavern', 'Milestone Reservoir IV',
  'Desert Spring', 'Amber Aquifer', 'Speed Serpents', 'Furnace Flats', 'Sludge Trench',
  'Flash Flood', 'Mirage Pool', 'Viper Domain', 'Baking Sands', 'Milestone Reservoir V',
  'Scorched Spring', 'Blazing Brook', 'Swift Vipers', 'Parched Mesa', 'Industrial Leak',
  'High Noon Rush', 'Oasis Gem', 'Snake Den', 'Drought Storm', 'Milestone Reservoir VI',
  'Delta Spring', 'Rivermouth Pool', 'River Vipers', 'Dry Estuary', 'Toxic Delta',
  'Tide Rush', 'Lotus Spring', 'Viper Marsh', 'Cracked Shore', 'Milestone Reservoir VII',
  'Channel Spring', 'Deep Basin', 'Cobras Nest', 'Sunken Sludge', 'Chemical Flats',
  'Storm Current', 'Healing Well', 'Serpent Ridge', 'Barren Delta', 'Milestone Reservoir VIII',
  'Sanctuary Spring', 'Sacred Pool', 'Viper Vanguard', 'Drought Bastion', 'Sludge Barrier',
  'Clockwork Rush', 'Eden Spring', 'Great Snake Nest', 'Scorched Gates', 'Milestone Reservoir IX',
  'Eternal Spring', 'Grand Aquifer', 'Apex Vipers', 'Final Drought Wave', 'Mega Toxic Spill',
  'Grand Time Attack', 'Immortal Oasis', 'Colossal Snake Den', 'The Final Gauntlet', 'The Centennial Reservoir'
];

function generate100Levels(): LevelConfig[] {
  const levels: LevelConfig[] = [];

  for (let i = 1; i <= 100; i++) {
    const zoneIndex = Math.min(4, Math.floor((i - 1) / 20));
    const zoneName = `Zone ${zoneIndex + 1}: ${ZONE_NAMES[zoneIndex]}`;
    const subtitle = LEVEL_SUBTITLES[i - 1] || `Level ${i} Adventure`;

    let gridWidth = 15;
    let gridHeight = 13;
    let requiredWater = 5;
    let cleanDropsCount = 5;
    let contaminatedDropsCount = 0;
    let snakesCount = 2;
    let heartsCount = 3;
    let dryAreasCount = 0;
    let hasTimer = false;
    let timeLimitSec = 0;
    let snakeMoveInterval = 650;
    let twist: LevelTwist = 'STANDARD';
    let twistTitle = 'Standard Exploration';
    let twistBadge = '💧 Clear Springs';

    if (i === 1) {
      // Level 1: The First Drop (small simple maze, 5 drops, 2 snakes, 3 hearts, no time limit)
      gridWidth = 15;
      gridHeight = 13;
      requiredWater = 5;
      cleanDropsCount = 6;
      contaminatedDropsCount = 0;
      snakesCount = 2;
      heartsCount = 3;
      dryAreasCount = 0;
      hasTimer = false;
      timeLimitSec = 0;
      snakeMoveInterval = 700;
      twist = 'STANDARD';
      twistTitle = 'The First Drop';
      twistBadge = '💧 5 Drops Needed';
    } else if (i === 2) {
      // Level 2: The Longer Journey (larger maze, dead ends, 5 snakes, 2 hearts, 7 drops required)
      gridWidth = 19;
      gridHeight = 15;
      requiredWater = 7;
      cleanDropsCount = 9;
      contaminatedDropsCount = 0;
      snakesCount = 5;
      heartsCount = 2;
      dryAreasCount = 0;
      hasTimer = false;
      timeLimitSec = 0;
      snakeMoveInterval = 620;
      twist = 'STANDARD';
      twistTitle = 'The Longer Journey';
      twistBadge = '🗺️ 7 Drops Needed';
    } else if (i === 3) {
      // Level 3: Water Is Running Low (larger & harder, 6 snakes, 2 hearts, dry areas -1 water, 8 water required)
      gridWidth = 21;
      gridHeight = 17;
      requiredWater = 8;
      cleanDropsCount = 10;
      contaminatedDropsCount = 0;
      snakesCount = 6;
      heartsCount = 2;
      dryAreasCount = 7;
      hasTimer = false;
      timeLimitSec = 0;
      snakeMoveInterval = 580;
      twist = 'DROUGHT_STORM';
      twistTitle = 'Drought Heat Wave';
      twistBadge = '🔥 Dry Areas (-1💧)';
    } else if (i === 4) {
      // Level 4: The Water Is Contaminated (clean drops +1, contaminated -1, 7 snakes, 2 hearts, 10 clean water required)
      gridWidth = 23;
      gridHeight = 19;
      requiredWater = 10;
      cleanDropsCount = 13;
      contaminatedDropsCount = 6;
      snakesCount = 7;
      heartsCount = 2;
      dryAreasCount = 0;
      hasTimer = false;
      timeLimitSec = 0;
      snakeMoveInterval = 540;
      twist = 'TOXIC_SPILL';
      twistTitle = 'Toxic Sludge Outbreak';
      twistBadge = '☣️ Contaminated Water';
    } else if (i === 5) {
      // Level 5: Save the Community (biggest/difficult maze, 8 snakes, 2 hearts, clean & contaminated, dry areas, timer, 12 clean water points)
      gridWidth = 25;
      gridHeight = 21;
      requiredWater = 12;
      cleanDropsCount = 16;
      contaminatedDropsCount = 7;
      snakesCount = 8;
      heartsCount = 2;
      dryAreasCount = 8;
      hasTimer = true;
      timeLimitSec = 90;
      snakeMoveInterval = 500;
      twist = 'TIME_ATTACK';
      twistTitle = 'Save the Community Rush';
      twistBadge = '⏳ 90s Timer & Hazards';
    } else {
      // Levels 6 - 100: Dynamic scaling across zones and rotating gameplay twists
      const baseW = 19 + Math.floor((i / 100) * 10);
      const baseH = 17 + Math.floor((i / 100) * 8);
      gridWidth = baseW % 2 === 0 ? baseW + 1 : baseW;
      gridHeight = baseH % 2 === 0 ? baseH + 1 : baseH;

      requiredWater = Math.min(18, 6 + Math.floor(i * 0.12));

      if (i % 10 === 0) {
        twist = 'CENTURY_CHALLENGE';
        twistTitle = `Grand Reservoir Milestone ${i / 10}`;
        twistBadge = '🏆 Grand Milestone';
        requiredWater += 3;
      } else {
        const cycle = i % 8;
        switch (cycle) {
          case 1:
            twist = 'SPRING_OASIS';
            twistTitle = 'Spring Oasis Blessing';
            twistBadge = '✨ Extra Hearts';
            break;
          case 2:
            twist = 'FAST_SNAKES';
            twistTitle = 'Agile Viper Surge';
            twistBadge = '⚡ Fast Snakes';
            break;
          case 3:
            twist = 'DROUGHT_STORM';
            twistTitle = 'Drought Heat Wave';
            twistBadge = '🔥 Drought Zones';
            break;
          case 4:
            twist = 'TOXIC_SPILL';
            twistTitle = 'Toxic Sludge Leak';
            twistBadge = '☣️ Toxic Sludge';
            break;
          case 5:
            twist = 'TIME_ATTACK';
            twistTitle = 'Rapid Delivery Rush';
            twistBadge = '⏳ Time Attack';
            break;
          case 6:
            twist = 'SNAKE_DEN';
            twistTitle = 'Snake Den Patrol';
            twistBadge = '🐍 Snake Dens';
            break;
          case 7:
            twist = 'MEGA_RESERVOIR';
            twistTitle = 'Mega Community Reservoir';
            twistBadge = '🌊 Mega Reservoir';
            requiredWater += 2;
            break;
          case 0:
            twist = 'DESERT_MIRAGE';
            twistTitle = 'Desert Heat Mirage';
            twistBadge = '🌪️ Desert Mirage';
            break;
        }
      }

      cleanDropsCount = requiredWater + 4 + Math.floor(i * 0.08);

      if (twist === 'TOXIC_SPILL' || twist === 'CENTURY_CHALLENGE' || i >= 30) {
        contaminatedDropsCount = twist === 'TOXIC_SPILL' ? 6 + Math.floor(i * 0.08) : 4 + Math.floor(i * 0.05);
      }

      snakesCount = Math.min(10, 3 + Math.floor(i * 0.07) + (twist === 'SNAKE_DEN' || twist === 'FAST_SNAKES' ? 2 : 0));
      heartsCount = twist === 'SPRING_OASIS' ? 4 : (i % 2 === 0 ? 3 : 2);

      if (twist === 'DROUGHT_STORM' || twist === 'DESERT_MIRAGE' || twist === 'CENTURY_CHALLENGE' || (i >= 20 && i % 3 === 0)) {
        dryAreasCount = 6 + Math.floor(i * 0.1);
      }

      snakeMoveInterval = Math.max(340, 600 - Math.floor(i * 2.5));
      if (twist === 'FAST_SNAKES') {
        snakeMoveInterval = Math.max(300, snakeMoveInterval - 100);
      }

      hasTimer = twist === 'TIME_ATTACK' || twist === 'CENTURY_CHALLENGE' || (i >= 40 && i % 5 === 0);
      timeLimitSec = hasTimer ? Math.max(50, 105 - Math.floor(i * 0.5)) : 0;
    }

    const infoPair = FACTS_AND_TIPS[(i - 1) % FACTS_AND_TIPS.length];

    levels.push({
      id: i,
      name: `Level ${i}: ${subtitle}`,
      subtitle,
      description: `Zone ${zoneIndex + 1}: ${twistTitle}. Gather at least ${requiredWater} clean water drops in your plastic bottle and deliver them safely to the Community Water Tank!`,
      twist,
      twistTitle,
      twistBadge,
      zoneName,
      gridWidth,
      gridHeight,
      requiredWater,
      cleanDropsCount,
      contaminatedDropsCount,
      snakesCount,
      heartsCount,
      dryAreasCount,
      hasTimer,
      timeLimitSec,
      snakeMoveInterval,
      educationalFact: infoPair.fact,
      educationalTip: infoPair.tip,
    });
  }

  return levels;
}

export const LEVELS: LevelConfig[] = generate100Levels();

