import { LevelConfig } from '../types';

export const GAME_LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Barangay Meadows',
    subtitle: 'Province Countryside Warm-Up',
    theme: 'countryside',
    distanceToSafeZone: 600,
    timeLimitSeconds: 45,
    obstacleFrequency: 1.0,
    obstacleTypes: ['ROLLING_ROCK', 'ROLLING_LOG', 'TREE_TRUNK'],
    speedMultiplier: 1.0,
    backgroundColors: {
      skyTop: '#4BA3E3',
      skyBottom: '#CBE5FE',
      mountains: '#79A2D8',
      hills: '#5CA96A',
      trees: '#2E7D32',
      ground: '#388E3C',
      road: '#C2A374',
    },
    description: 'Alexander begins his sprint through the sunny fields. Dodge tumbling river pebbles and rolling logs to reach the first village safe post!',
  },
  {
    id: 2,
    name: 'Bamboo Rapids Valley',
    subtitle: 'Fast-Rolling Timber & Mud Pits',
    theme: 'forest',
    distanceToSafeZone: 850,
    timeLimitSeconds: 50,
    obstacleFrequency: 1.25,
    obstacleTypes: ['ROLLING_LOG', 'TREE_TRUNK', 'SWINGING_BRANCH', 'MUD_PIT'],
    speedMultiplier: 1.15,
    backgroundColors: {
      skyTop: '#2C5E7A',
      skyBottom: '#85B3C8',
      mountains: '#406A7C',
      hills: '#2D6A4F',
      trees: '#1B4332',
      ground: '#2D5A27',
      road: '#8D6E63',
    },
    description: 'Deep in the province woods, foresters are clearing heavy tree trunks. Watch out for rolling lumber and muddy patches!',
  },
  {
    id: 3,
    name: 'Volcanic Foothills',
    subtitle: 'Bouncing Boulders & Rocky Slopes',
    theme: 'rocky_mountain',
    distanceToSafeZone: 1100,
    timeLimitSeconds: 58,
    obstacleFrequency: 1.45,
    obstacleTypes: ['BOUNCING_BOULDER', 'ROLLING_ROCK', 'TREE_TRUNK', 'MUD_PIT'],
    speedMultiplier: 1.25,
    backgroundColors: {
      skyTop: '#E65100',
      skyBottom: '#FFE082',
      mountains: '#5D4037',
      hills: '#8D6E63',
      trees: '#4E342E',
      ground: '#6D4C41',
      road: '#A1887F',
    },
    description: 'Steep inclines and tumbling boulders roll down the volcanic slope. Jump with precision to preserve Alexander’s 3 lives!',
  },
  {
    id: 4,
    name: 'The Legend Ridge',
    subtitle: 'Final Dash to the Province Safe Zone',
    theme: 'legend_ridge',
    distanceToSafeZone: 1350,
    timeLimitSeconds: 65,
    obstacleFrequency: 1.7,
    obstacleTypes: ['BOUNCING_BOULDER', 'ROLLING_ROCK', 'ROLLING_LOG', 'TREE_TRUNK', 'SWINGING_BRANCH'],
    speedMultiplier: 1.35,
    backgroundColors: {
      skyTop: '#311B92',
      skyBottom: '#FF8A80',
      mountains: '#4A148C',
      hills: '#6A1B9A',
      trees: '#880E4F',
      ground: '#2E7D32',
      road: '#E0A96D',
    },
    description: 'The crowning challenge! Sprint at top velocity through high-speed tumbling trunks and boulders to enter the glorious Safe Zone Citadel!',
  },
  {
    id: 99,
    name: 'Infinite Province Odyssey',
    subtitle: 'Endless Marathon • Escalating Difficulty',
    theme: 'legend_ridge',
    distanceToSafeZone: 999999999,
    timeLimitSeconds: 0,
    obstacleFrequency: 1.2,
    obstacleTypes: ['ROLLING_ROCK', 'ROLLING_LOG', 'TREE_TRUNK', 'BOUNCING_BOULDER', 'SWINGING_BRANCH', 'MUD_PIT'],
    speedMultiplier: 1.1,
    isInfinite: true,
    backgroundColors: {
      skyTop: '#0F172A',
      skyBottom: '#0D9488',
      mountains: '#1E293B',
      hills: '#065F46',
      trees: '#047857',
      ground: '#064E3B',
      road: '#B45309',
    },
    description: 'Endless survival test! As time passes, your runner accelerates, obstacles spawn faster, rolling hazards gain speed, and biomes continuously transform. How long can you survive?',
  },
];

export const INFINITE_LEVEL = GAME_LEVELS[4];
